name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (without submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up SSH access for private submodule
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOTFILES_CI_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Rewrite GitHub URLs to use SSH instead of HTTPS
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Manually init submodules
        run: git submodule update --init --recursive
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir ./install
